### ISSUE TITLE
Might be easier to use Uri class

### ISSUE THREAD

**Issue by thosakwe** [r-unruh/youtube_parser#1]
There's a `Uri` utility class in `dart:core` that might make the logic of this package easier, especially since you wouldn't need regexes anymore:

```dart
var uri = Uri.parse('https://www.youtube.com/watch?v=CBWlfU_na-2');
// Check uri.host == youtube.com or m.youtube.com, etc.
var videoId = uri.queryParameters['v'];
```

**Comment by r-unruh** [comment]
You're right, this makes the whole thing a bit simpler and less error-prone. Thanks! 72f9f78a06dd3c894091bb3de435bf81868d75e3
