### ISSUE TITLE
getIdFromUrl returns null on correct youtube url

### ISSUE THREAD

**Issue by MalteMagnussen** [r-unruh/youtube_parser#3]
This URL: https://www.youtube.com/embed/VYWjxvm14Pk?rel=0

Returns null for some reason, when using `getIdFromUrl`

Instead of `VYWjxvm14Pk`

and I don't know why.

**Comment by r-unruh** [comment]
You are using an "embed" url, but this library doesn't accept those at the time.

Acceptable urls would look like this:
https://www.youtube.com/watch?v=VYWjxvm14Pk
https://m.youtube.com/watch?v=VYWjxvm14Pk
https://youtu.be/VYWjxvm14Pk

**Comment by r-unruh** [comment]
> This URL: https://www.youtube.com/embed/VYWjxvm14Pk?rel=0
> 
> Returns null for some reason, when using `getIdFromUrl`
> 
> Instead of `VYWjxvm14Pk`

The library now supports this type of url as of 2.1.0 and should return the expected value.
