### ISSUE TITLE
shorts url without www

### ISSUE THREAD

**Issue by Dieterbe** [r-unruh/youtube_parser#4]
Hi,
FYI, it seems this is a valid URL:
```
https://youtube.com/shorts/8DmLrGJRB5k?si=AOhyCfuma6b39Btz&t=7
```
However, for shorts, this library only seems to support urls in the form `www.youtube.com/shorts`

no big deal, i just do a string replace, but could be nice to fix.

Dieter

**Comment by r-unruh** [comment]
Thanks!
